### ISSUE TITLE
Does this code have the corresponding paper?

### ISSUE THREAD

**Issue by HandsomeWeiC** [Xz-Alan/TAFFN#1]
Hello, I am interested in the code about the fusion of SAR and Optical images. So I wonder that whether the presented code has the corresponding paper so that the whole idea can be fully understood. By the way, are you a student of Northwestern Polytechnical University,  Xi'an Shaanxi, P.R.China? I come from the school of computer science, NWPU.

**Comment by Xz-Alan** [comment]
Ahhh, I am from the School of Electronic and Information. Nice to meet you~
This paper will be presented at IGARSS2021, and it has not been published yet.
BTW, Star it if you 👍 it !

**Comment by HandsomeWeiC** [comment]
能先邮箱发我一份吗？想看看大佬的论文！谢谢啦！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xz-Alan/TAFFN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月12日(星期三) 下午2:58
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [Xz-Alan/TAFFN] Does this code have the corresponding paper? (#1)





 
Ahhh, I am from the School of Electronic Information. Nice to meet you~
 This paper will be presented at IGARSS2021, and it has not been published yet.

**Comment by Xz-Alan** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    最近还需要小修一下，大概6月1号以后可以给你发一份。不过这个论文的思路讲真比较水啦，和代码里实现的差不多，主要思想就是空间和光谱的注意力机制特征进行融合。

    On 05/12/2021 ***@***.***> wrote： 




能先邮箱发我一份吗？想看看大佬的论文！谢谢啦！



















------------------&nbsp;原始邮件&nbsp;------------------



发件人:                                                                                                                        "Xz-Alan/TAFFN"                                                                                    ***@***.***&gt;;



发送时间:&nbsp;2021年5月12日(星期三) 下午2:58



***@***.***&gt;;



***@***.******@***.******@***.***&gt;;



主题:&nbsp;Re: [Xz-Alan/TAFFN] Does this code have the corresponding paper? (#1)























 



Ahhh, I am from the School of Electronic Information. Nice to meet you~



 This paper will be presented at IGARSS2021, and it has not been published yet.

**Comment by HandsomeWeiC** [comment]
好嘞，谢谢啦，最近老师让我调研SAR图像与光学图像的融合学习方法，大佬有推荐的论文和code吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xz-Alan/TAFFN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月12日(星期三) 下午4:30
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [Xz-Alan/TAFFN] Does this code have the corresponding paper? (#1)





 
 
      
 
 
 
     font{ 
         line-height: 1.6; 
     } 
     ul,ol{ 
         padding-left: 20px; 
         list-style-position: inside; 
     } 
 
 
     
     最近还需要小修一下，大概6月1号以后可以给你发一份。不过这个论文的思路讲真比较水啦，和代码里实现的差不多，主要思想就是空间和光谱的注意力机制特征进行融合。
 
     On 05/12/2021 ***@***.***&gt; wrote： 
 
 
 
 
 能先邮箱发我一份吗？想看看大佬的论文！谢谢啦！
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 
 
 
 发件人:                                                                                                                        "Xz-Alan/TAFFN"                                                                                    ***@***.***&amp;gt;;
 
 
 
 发送时间:&amp;nbsp;2021年5月12日(星期三) 下午2:58
 
 
 
 ***@***.***&amp;gt;;
 
 
 
 ***@***.******@***.******@***.***&amp;gt;;
 
 
 
 主题:&amp;nbsp;Re: [Xz-Alan/TAFFN] Does this code have the corresponding paper? (#1)
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
  
 
 
 
 Ahhh, I am from the School of Electronic Information. Nice to meet you~
 
 
 
  This paper will be presented at IGARSS2021, and it has not been published yet.

**Comment by Xz-Alan** [comment]
我也是刚刚入坑而已，不是大佬（误我把我之前看过的一些论文发给你吧，除了SAR-optical的，也可以看看HSI-LIDAR或者其他多模态的论文。
https://xpulsar.com/share/b557f9a6ada83a9ed9aa6c084b09a459
这个链接可直接下载，但是7天后就会过期，记得提前保存
PS: 以后私下也可多多交流如何科(guan)研(shui)
----- 原始邮件 -----
发件人：HandsomeWeiC ***@***.***>
收件人：Xz-Alan/TAFFN ***@***.***>
抄送人：xuzhe_nwpu ***@***.***>,  Comment ***@***.***>
主题：Re: [Xz-Alan/TAFFN] Does this code have the corresponding paper? (#1)
日期：2021年05月12日 16点16分



能先邮箱发我一份吗？想看看大佬的论文！谢谢啦！
























------------------ 原始邮件 ------------------




发件人:                                                                                                                        "Xz-Alan/TAFFN"                                                                                    ***@***.***&gt;;




发送时间: 2021年5月12日(星期三) 下午2:58




***@***.***&gt;;




***@***.******@***.******@***.***&gt;;




主题: Re: [Xz-Alan/TAFFN] Does this code have the corresponding paper? (#1)





























 




Ahhh, I am from the School of Electronic Information. Nice to meet you~




 This paper will be presented at IGARSS2021, and it has not been published yet.

**Comment by HandsomeWeiC** [comment]
好嘞，感谢！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xz-Alan/TAFFN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月13日(星期四) 下午2:48
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [Xz-Alan/TAFFN] Does this code have the corresponding paper? (#1)





 我也是刚刚入坑而已，不是大佬（误我把我之前看过的一些论文发给你吧，除了SAR-optical的，也可以看看HSI-LIDAR或者其他多模态的论文。
 https://xpulsar.com/share/b557f9a6ada83a9ed9aa6c084b09a459
 这个链接可直接下载，但是7天后就会过期，记得提前保存
 PS: 以后私下也可多多交流如何科(guan)研(shui)
 ----- 原始邮件 -----
 发件人：HandsomeWeiC ***@***.***&gt;
 收件人：Xz-Alan/TAFFN ***@***.***&gt;
 抄送人：xuzhe_nwpu ***@***.***&gt;,  Comment ***@***.***&gt;
 主题：Re: [Xz-Alan/TAFFN] Does this code have the corresponding paper? (#1)
 日期：2021年05月12日 16点16分
 
 
 
 能先邮箱发我一份吗？想看看大佬的论文！谢谢啦！ 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 
 
 
 
 发件人:                                                                                                                        "Xz-Alan/TAFFN"                                                                                    ***@***.***&amp;gt;; 
 
 
 
 
 发送时间: 2021年5月12日(星期三) 下午2:58 
 
 
 
 
 ***@***.***&amp;gt;; 
 
 
 
 
 ***@***.******@***.******@***.***&amp;gt;; 
 
 
 
 
 主题: Re: [Xz-Alan/TAFFN] Does this code have the corresponding paper? (#1) 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
   
 
 
 
 
 Ahhh, I am from the School of Electronic Information. Nice to meet you~ 
 
 
 
 
  This paper will be presented at IGARSS2021, and it has not been published yet.
