### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by yisun98** [Xz-Alan/TAFFN#2]
您好，我对您的工作非常感兴趣，我初步了解SAR和光学图像融合用于遥感地物分类，不知道您可否分享一下论文中的数据集，仅限学习使用。看到您也是西北工业大学的学生，我来自计算机学院！

**Comment by Xz-Alan** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    您好，感谢对这个工作感兴趣，但是这个数据集是研究所那边提供的，我不确定能不能公开，我需要问问导师再给您回复。
    
        
            
        
    
    
         
        
             
        
    
     

    在2022年5月13日 ***@***.***> 写道： 




您好，我对您的工作非常感兴趣，我初步了解SAR和光学图像融合用于遥感地物分类，不知道您可否分享一下论文中的数据集，仅限学习使用。看到您也是西北工业大学的学生，我来自计算机学院！

**Comment by yisun98** [comment]
好的好的，期待您的回复。

**Comment by Xz-Alan** [comment]
不好意思，这个数据集归属于研究所，暂时还不公开，你可以找找其他公开的数据集。
飞桨AI有一个遥感数据集汇总，你可以在那个上面找找看
https://aistudio.baidu.com/aistudio/projectdetail/882508
